[[protocols]]
name = "Hama_Big_Zapper"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x4824ff = "KEY_POWER"
0x48249f = "KEY_VOLUMEUP"
0x48241f = "KEY_VOLUMEDOWN"
0x4824bf = "KEY_CHANNELUP"
0x48243f = "KEY_CHANNELDOWN"
0x4824df = "KEY_MUTE"
### 0x482457 = "KEY_EXIT"
0x4824c7 = "KEY_NUMERIC_1"
0x482447 = "KEY_NUMERIC_2"
0x482487 = "KEY_NUMERIC_3"
0x4824fd = "KEY_NUMERIC_4"
0x48247d = "KEY_NUMERIC_5"
0x4824bd = "KEY_NUMERIC_6"
0x4824dd = "KEY_NUMERIC_7"
0x48245d = "KEY_NUMERIC_8"
0x48249d = "KEY_NUMERIC_9"
0x48241d = "KEY_NUMERIC_0"
0x48248f = "KEY_AUDIO"
0x482457 = "KEY_OK"
0x482477 = "KEY_MENU"
0x482407 = "KEY_MODE"
